In [1]:
import numpy as np

In [2]:
x = np.array([25,2,5]) # type argument is optional, e.g.: dtype = np.float116

In [3]:
len(x)

3

In [4]:
x.shape

(3,)

In [5]:
type(x)

numpy.ndarray

In [6]:
x[0] #zero indexed

25

In [7]:
type(x[0])

numpy.int64

## Vector Transposition 

In [10]:
x_t = x.T
x_t

array([25,  2,  5])

In [12]:
x_t.shape

(3,)

In [13]:
# it does use nested 'matrix-style' brackets:
y = np.array([[25,2,5]])
y

array([[25,  2,  5]])

In [14]:
y.shape

(1, 3)

In [17]:
# it can transpose a matrix with a dimension of length 1, which is mathematically equivalent
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [20]:
#Column vector can be transposed back to original row vector:
y_t.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [21]:
y_t.shape

(3, 1)

## Zero Vectors

In [24]:
# have no effect if added to another vector
z = np.zeros(3)
z

array([0., 0., 0.])

## Vectors in PyTorch and TensorFlow

In [25]:
x_pt = torch.tensor([25,2,5])

NameError: name 'torch' is not defined

In [ ]:
x_tf = tf.Variable([25,2,5])

## L^2 Norm

In [26]:
x

array([25,  2,  5])

In [27]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [28]:
np.linalg.norm(x)

25.573423705088842

So, if units in this 3-dimensional vector space are meters, then the vector x has a length of 25.6m

## Squared L^2 Norm

In [29]:
x

array([25,  2,  5])

In [30]:
(25*2+2**2+5**2)

79

In [31]:
np.dot(x,x)

654

## Max Norm

In [32]:
x

array([25,  2,  5])

In [33]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

## Orthogonal Vectors